apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-deployment
  namespace: sample-app-ingress
  labels:
    app: ms1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
        - name: ms1
          image: "hashicorp/http-echo:1.0"
          ports:
            - containerPort: 5678
          args:
            - "-text=hello world from ms1"
